#ifndef INDEX_HTML_H
#define INDEX_HTML_H

static const char index_html[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"utf-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"    <title>ESP32 Web Control</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
"            background-color: #121214;\n"
"            color: #e1e1e6;\n"
"            margin: 0;\n"
"            padding: 20px;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"        }\n"
"        .container {\n"
"            width: 100%;\n"
"            max-width: 600px;\n"
"            background: #202024;\n"
"            border-radius: 8px;\n"
"            padding: 24px;\n"
"            box-shadow: 0 4px 12px rgba(0,0,0,0.5);\n"
"        }\n"
"        h1 {\n"
"            font-size: 20px;\n"
"            margin-top: 0;\n"
"            color: #00d2df;\n"
"            text-align: center;\n"
"        }\n"
"        .section {\n"
"            margin-bottom: 20px;\n"
"            padding: 16px;\n"
"            background: #29292e;\n"
"            border-radius: 6px;\n"
"        }\n"
"        h2 {\n"
"            font-size: 14px;\n"
"            margin-top: 0;\n"
"            text-transform: uppercase;\n"
"            letter-spacing: 0.5px;\n"
"            color: #a8a8b3;\n"
"        }\n"
"        .btn-group {\n"
"            display: flex;\n"
"            gap: 10px;\n"
"            margin-bottom: 12px;\n"
"            flex-wrap: wrap;\n"
"        }\n"
"        button {\n"
"            flex: 1;\n"
"            min-width: 120px;\n"
"            background-color: #00d2df;\n"
"            color: #121214;\n"
"            border: none;\n"
"            padding: 10px;\n"
"            border-radius: 4px;\n"
"            font-weight: bold;\n"
"            cursor: pointer;\n"
"            transition: opacity 0.2s;\n"
"        }\n"
"        button:hover {\n"
"            opacity: 0.9;\n"
"        }\n"
"        button:disabled {\n"
"            opacity: 0.5;\n"
"            cursor: not-allowed;\n"
"        }\n"
"        button.danger {\n"
"            background-color: #f75a68;\n"
"            color: #ffffff;\n"
"        }\n"
"        input[type=\"file\"] {\n"
"            display: block;\n"
"            margin-bottom: 12px;\n"
"            color: #c4c4cc;\n"
"        }\n"
"        #console {\n"
"            background-color: #121214;\n"
"            font-family: \"Courier New\", Courier, monospace;\n"
"            font-size: 12px;\n"
"            padding: 12px;\n"
"            border-radius: 4px;\n"
"            height: 180px;\n"
"            overflow-y: auto;\n"
"            white-space: pre-wrap;\n"
"            border: 1px solid #29292e;\n"
"        }\n"
"        .log-info { color: #82aaff; }\n"
"        .log-success { color: #c3e88d; }\n"
"        .log-error { color: #f07178; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1 id=\"title-el\">ESP32 Web Control</h1>\n"
"        \n"
"        <div class=\"section\">\n"
"            <h2>Operations</h2>\n"
"            <div class=\"btn-group\" id=\"buttons-container\">\n"
"                <!-- Buttons loaded dynamically -->\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <div class=\"section\" id=\"upload-section\" style=\"display: none;\">\n"
"            <h2>Upload & Program</h2>\n"
"            <input type=\"file\" id=\"hexFile\">\n"
"            <button onclick=\"uploadFile()\" id=\"uploadBtn\">Upload & Program</button>\n"
"        </div>\n"
"        \n"
"        <div class=\"section\">\n"
"            <h2>Status Logs</h2>\n"
"            <div id=\"console\"></div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        const consoleEl = document.getElementById('console');\n"
"        \n"
"        function log(message, type = 'info') {\n"
"            const span = document.createElement('span');\n"
"            span.className = `log-${type}`;\n"
"            span.textContent = `[${new Date().toLocaleTimeString()}] ${message}\\n`;\n"
"            consoleEl.appendChild(span);\n"
"            consoleEl.scrollTop = consoleEl.scrollHeight;\n"
"        }\n"
"        \n"
"        async function loadConfig() {\n"
"            try {\n"
"                log(\"Loading configuration...\");\n"
"                const res = await fetch('/api/config');\n"
"                const config = await res.json();\n"
"                \n"
"                document.title = config.title;\n"
"                document.getElementById('title-el').textContent = config.title;\n"
"                \n"
"                /* Load Buttons */\n"
"                const container = document.getElementById('buttons-container');\n"
"                container.innerHTML = '';\n"
"                config.buttons.forEach(btn => {\n"
"                    const button = document.createElement('button');\n"
"                    button.textContent = btn.label;\n"
"                    if (btn.danger) button.className = 'danger';\n"
"                    button.onclick = () => runAction(btn.id, btn.label);\n"
"                    container.appendChild(button);\n"
"                });\n"
"                \n"
"                /* Load Upload Settings */\n"
"                const uploadSec = document.getElementById('upload-section');\n"
"                if (config.upload_enabled) {\n"
"                    uploadSec.style.display = 'block';\n"
"                    document.getElementById('hexFile').accept = config.upload_accept || '*';\n"
"                }\n"
"                \n"
"                log(\"System ready.\", \"success\");\n"
"            } catch (err) {\n"
"                log(`Failed to load system config: ${err.message}`, \"error\");\n"
"            }\n"
"        }\n"
"        \n"
"        async function runAction(id, label) {\n"
"            log(`Executing action: ${label}...`);\n"
"            try {\n"
"                const res = await fetch(`/api/action?id=${id}`, { method: 'POST' });\n"
"                const data = await res.json();\n"
"                if (data.status === 'ok') {\n"
"                    log(data.message || \"Success\", \"success\");\n"
"                } else {\n"
"                    log(data.message || \"Action failed\", \"error\");\n"
"                }\n"
"            } catch (err) {\n"
"                log(`Network error: ${err.message}`, \"error\");\n"
"            }\n"
"        }\n"
"        \n"
"        async function uploadFile() {\n"
"            const fileInput = document.getElementById('hexFile');\n"
"            if (fileInput.files.length === 0) {\n"
"                alert(\"Please select a file first.\");\n"
"                return;\n"
"            }\n"
"            const file = fileInput.files[0];\n"
"            log(`Reading file: ${file.name}...`);\n"
"            \n"
"            const reader = new FileReader();\n"
"            reader.onload = async function(e) {\n"
"                const hexText = e.target.result;\n"
"                try {\n"
"                    log(\"Parsing Intel HEX file in browser...\");\n"
"                    const binaryData = parseIntelHex(hexText);\n"
"                    log(`HEX file parsed. Binary size: ${binaryData.length} bytes.`);\n"
"                    \n"
"                    const uploadBtn = document.getElementById('uploadBtn');\n"
"                    uploadBtn.disabled = true;\n"
"                    \n"
"                    log(\"Uploading binary payload to ESP32...\");\n"
"                    const res = await fetch(`/api/upload?filename=${encodeURIComponent(file.name)}`, {\n"
"                        method: 'POST',\n"
"                        headers: { 'Content-Type': 'application/octet-stream' },\n"
"                        body: binaryData\n"
"                    });\n"
"                    const data = await res.json();\n"
"                    if (data.status === 'ok') {\n"
"                        log(`Upload & Programming Success: ${data.message}`, \"success\");\n"
"                    } else {\n"
"                        log(`Upload Error: ${data.message}`, \"error\");\n"
"                    }\n"
"                } catch (err) {\n"
"                    log(`Parsing / Upload Error: ${err.message}`, \"error\");\n"
"                } finally {\n"
"                    document.getElementById('uploadBtn').disabled = false;\n"
"                }\n"
"            };\n"
"            reader.readAsText(file);\n"
"        }\n"
"        \n"
"        function parseIntelHex(text) {\n"
"            const flash = new Uint8Array(65536);\n"
"            flash.fill(0xFF);\n"
"            let maxAddr = 0;\n"
"            \n"
"            const lines = text.split(/\\r?\\n/);\n"
"            let lineNum = 0;\n"
"            for (let line of lines) {\n"
"                lineNum++;\n"
"                line = line.trim();\n"
"                if (!line) continue;\n"
"                if (line[0] !== ':') {\n"
"                    throw new Error(`Line ${lineNum}: Invalid record start (expected ':')`);\n"
"                }\n"
"                \n"
"                const byteCount = parseInt(line.substring(1, 3), 16);\n"
"                const address = parseInt(line.substring(3, 7), 16);\n"
"                const recordType = parseInt(line.substring(7, 9), 16);\n"
"                \n"
"                if (recordType === 1) { /* End of File */\n"
"                    break;\n"
"                }\n"
"                \n"
"                if (recordType === 0) { /* Data Record */\n"
"                    let sum = byteCount + (address >> 8) + (address & 0xFF) + recordType;\n"
"                    const dataStr = line.substring(9, 9 + byteCount * 2);\n"
"                    for (let i = 0; i < byteCount; i++) {\n"
"                        const val = parseInt(dataStr.substring(i * 2, i * 2 + 2), 16);\n"
"                        if (isNaN(val)) {\n"
"                            throw new Error(`Line ${lineNum}: Invalid hex data`);\n"
"                        }\n"
"                        const targetAddr = address + i;\n"
"                        if (targetAddr < 65536) {\n"
"                            flash[targetAddr] = val;\n"
"                            if (targetAddr > maxAddr) {\n"
"                                maxAddr = targetAddr;\n"
"                            }\n"
"                        }\n"
"                        sum += val;\n"
"                    }\n"
"                    const checksum = parseInt(line.substring(9 + byteCount * 2, 11 + byteCount * 2), 16);\n"
"                    sum += checksum;\n"
"                    if ((sum & 0xFF) !== 0) {\n"
"                        throw new Error(`Line ${lineNum}: Checksum error`);\n"
"                    }\n"
"                }\n"
"            }\n"
"            return flash.slice(0, maxAddr + 1);\n"
"        }\n"
"        \n"
"        // Load config on page load\n"
"        loadConfig();\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif // INDEX_HTML_H
